apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmsamplechartapp-tst
  namespace: argocd
spec:
  project: default  
  destination:
    namespace: helmsamplechart-tst
    name: in-cluster  #update cluster name if its different
  source:
    repoURL: https://github.com/davidboukari/helmsamplechart.git
    path: charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-tst.yaml #any custom value file you want to apply.
  syncPolicy:
    syncOptions:
    - CreateNamespace=true          
