{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
{{ include "myproject.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.configmap.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}